### ISSUE TITLE
Recycling Bin

### ISSUE THREAD

**Issue by Jamiewarb** [hex-digital/lucidity-next-sanity-starter#2]

**Comment by liamb13** [comment]
I've followed this previously with some decent results; [Create a recycling bin for logging and restoring deleted documents](https://www.sanity.io/guides/bin-for-restoring-deleted-documents)

**Comment by Jamiewarb** [comment]
Yeah this is exactly the approach I'm considering. I have a slightly cleaned up version with fixed typing for this. Should be quick to drop into the repo

**Comment by Jamiewarb** [comment]
That's in now
